---
- hosts: linux
  gather_facts: true
  become: true
  
  tasks:
    - name: include vars
      include_vars:
        file: ../group_vars/services.yml
        name: inventory

    - name: ensure services
      service:
        name: "{{ item.name }}"
        state: "{{ item.state }}"
        enabled: "{{ item.enabled }}"
      loop: "{{ inventory[inventory_hostname]['services'].values() }}"
      when: item.get('enabled', None) is not none and item.get('state', None) is not none
    
