---
- hosts: linux
  gather_facts: true

  collections:
    - hanzoo7.reporting
  
  vars_files:
    - ../group_vars/report.yml

  tasks:
    - name: Get the status of all services
      service_facts:
      register: services_list

    - include_role:
        name: registerToYaml
      vars:
        inputs: "{{ services_list['ansible_facts']}}"


