---
- hosts: linux
  gather_facts: true
  serial: 1

  collections:
    - hanzoo7.reporting
  
  vars_files:
    - ../group_vars/report.yml

  tasks:
    - name: Get the status of all services
      service_facts:
      register: services_list

    - include_role:
        name: registerToYaml
      vars:
        insert: "{{ services_list['ansible_facts']['services']}}"
        node: "{{ inventory_hostname }}/services"

- hosts: localhost
  gather_facts: false

  collections:
    - hanzoo7.reporting
  
  vars_files:
    - ../group_vars/report.yml

  tasks:
    - include_role:
        name: transformYaml