---
- hosts: windows
  gather_facts: false
  serial: 1

  collections:
    - ansible.windows
  
  vars_files:
    - ../vaults/windows

  tasks:
    - name: Get the status of all services
      win_service_info:
      register: services_list

- hosts: localhost

  collections:
    - hanzoo7.reporting
  
  vars_files:
    - ../group_vars/report.yml

  tasks:
    - include_role:
        name: formatToYaml
      
      vars:
        insert: "{{ item.value.services_list.services }}"
        node: "{{ item.key }}/services"
      with_dict: "{{ hostvars }}"
      when: "'windows' in hostvars[item.key].group_names and '/opt/datas/projects/os_services/hosts/lab' in hostvars[item.key].ansible_inventory_sources"
