directory: ../files

get_config : 
  services: 
    enabled: true
    filter: status -eq 4
  features:
    enabled: true
    filter: InstallState -eq 1
  partitions:
    enabled: true
    filter: DriveType -eq "Fixed" | ? FileSystemLabel -ne "Réservé au système"
  packages:
    enabled: true
    filter:  
  firewall:
    enabled: true
    filter: enabled -eq $true