---
- hosts: windows
  gather_facts: true
  become_method: false
  
  collections:
    - hanzoo7.windows

  vars_files:
    - ../vaults/windows_ensure
    - ../group_vars/collect_params.yml

  tasks:
    - name: load configuration file
      include_vars:
        file: "{{ directory }}/{{ inventory_hostname }}.yml"
    
    - name : ensure partitions
      include_role:
        name: win_partitions
      vars:
        disk_number: "{{ item.disk_number }}"
        partition_number: "{{ item.partition_number }}"
        DriveLetter: "{{ item.DriveLetter }}"
        FileSystem: "{{ item.FileSystem }}"
        FileSystemLabel: "{{ item.FileSystemLabel }}"
        Size: "{{ item.Size }}"
        state: "{{ item.state }}"
      with_list: "{{ partitions }}"


        