---
- hosts: windows
  gather_facts: false
  become_method: runas
  
  vars_files:
    - ../vaults/windows_ensure
    - ../group_vars/collect_params.yml

  tasks:
    - name: load configuration file
      include_vars:
        file: "{{ directory }}/{{ inventory_hostname }}.yml"

    - name : ensure partitions
      community.windows.win_partition:
        drive_letter: "{{ item.drive_letter }}"
        partition_size: "{{ item.partition_size_in_bytes | default(item.partition_size) | default(-1)}}"
        disk_number: "{{ item.disk_number }}"
        partition_number: "{{ item.partition_number }}"
        state: "{{ item.state }}"
      with_list: "{{ partitions }}"

      

        