directory: ../files

get_config:
  services:
    enabled: true
    filter: resources[-1]['active'] == 'active'
  packages:
    enabled: true
    filter: resources[-1]['is_installed'] == True
  partitions:
    enabled: true
    filter: re.match("^/dev/sd.*$",resources[-1]['device'])
