---
- hosts: windows
  gather_facts: false
  become_method: runas
  ignore_errors: yes
  
  collections:
    - hanzoo7.windows  

  vars_files:
    - ../vaults/windows_ensure
    - ../files/adds.yml

  tasks:
    - include_role:
        name: ad_config
